### ISSUE TITLE
Add repro builds status

### ISSUE THREAD

**Issue by FFY00** [archlinux/archweb#244]
We should add a repro builds status indicator in the package page.

**Comment by jelly** [comment]
One idea is to import https://tests.reproducible-builds.org/archlinux/reproducible.json into our Database and generate a developer dashboard from it which can show your no reproducible packages and all.

For showing it in the packages detail view, the current status would confuse a user since it's just a CI and not reproducing actual packages.

**Comment by FFY00** [comment]
What if we put it in both places but hide it from the user in detail view? Sometimes I might want to check the repro state of the packages I am looking at.

But I am fine just adding it in the dashboard if you want to go for it.

**Comment by FFY00** [comment]
We could even add a field in the user preferences to opt out the repro state in detail view.

**Comment by jelly** [comment]
In short this means, we need the following parts to implement this:

* Introduce a new ReproStatus model with a Package relation, status field (reproducible,  FTBS,  FTBR_0,1,2??), bool or enum for CI or Verification build.
* Create a new management command to fetch and parse the JSON (use Last-modified header to check if there is an update?) and create ReproStatus models and match them to a Package in our repositories
* Create a new dashboard with options to filter for only the logged in Packager

**Comment by jelly** [comment]
Implemented in https://github.com/archlinux/archweb/commit/1a15dea6700eadc8379d0fef2e0b3f37de92c54e
