### ISSUE TITLE
Use Arch Linux blue for http links

### ISSUE THREAD

**Issue by jelly** [archlinux/archweb#315]
See security tracker:
```
a:link,
a:visited {
	color: #07b;
}
```

**Comment by sreeram514** [comment]
@jelly I am interested to work on this. 
I see http links are already with #07b color, could you tell which page you are referring to .

**Comment by jelly** [comment]
@anthraxx what was it again :)

**Comment by jelly** [comment]
> @jelly I am interested to work on this.
> I see http links are already with #07b color, could you tell which page you are referring to .

Oh, it's for on hoover, see hover on https://security.archlinux.org

**Comment by anthraxx** [comment]
It was #08c like the color picker reveals when picking our logo color

See here

https://gitlab.archlinux.org/archlinux/archlinux-common-style/-/blob/master/sass/generic.scss

**Comment by sreeram514** [comment]
> > @jelly I am interested to work on this.
> > I see http links are already with #07b color, could you tell which page you are referring to .
> 
> Oh, it's for on hoover, see hover on https://security.archlinux.org

Yeah, hoover is not working in security tracker it should be fixed in arch-security-tracker repo [here](https://github.com/archlinux/arch-security-tracker/blob/335c495433534d2e95e2e7adc8815ca439904d0f/tracker/static/style.css#L165). 
As @anthraxx  pointed color is #80c for logo, will make sure all hyperlinks has same color. Could you assign this to me
